export const themes = [
  {
    id: 'light',
    name: 'Светлая',
    description: 'Чистая светлая тема',
    type: 'light',
    colors: {
      primary: '#4f46e5',
      background: '#ffffff',
      surface: '#f8fafc',
      text: '#1f2937',
      border: '#e5e7eb',
    },
  },
  {
    id: 'dark',
    name: 'Темная',
    description: 'Элегантная темная тема',
    type: 'dark',
    colors: {
      primary: '#6366f1',
      background: '#0f172a',
      surface: '#1e293b',
      text: '#f1f5f9',
      border: '#334155',
    },
  },
  {
    id: 'nightowl',
    name: 'Night Owl',
    description: 'Тема вдохновленная редактором кода',
    type: 'dark',
    colors: {
      primary: '#7dd3fc',
      background: '#011627',
      surface: '#011e3c',
      text: '#d6deeb',
      border: '#1d3b53',
    },
  },
  {
    id: 'sunset',
    name: 'Закат',
    description: 'Теплые оранжевые тона',
    type: 'dark',
    colors: {
      primary: '#f97316',
      background: '#1c1917',
      surface: '#292524',
      text: '#fafaf9',
      border: '#57534e',
    },
  },
  {
    id: 'forest',
    name: 'Лес',
    description: 'Успокаивающая зеленая тема',
    type: 'dark',
    colors: {
      primary: '#22c55e',
      background: '#052e16',
      surface: '#14532d',
      text: '#f0fdf4',
      border: '#166534',
    },
  },
  {
    id: 'ocean',
    name: 'Океан',
    description: 'Глубокие синие тона',
    type: 'dark',
    colors: {
      primary: '#06b6d4',
      background: '#164e63',
      surface: '#0e7490',
      text: '#f0fdfd',
      border: '#0891b2',
    },
  },
  {
    id: 'lavender',
    name: 'Лаванда',
    description: 'Нежная фиолетовая тема',
    type: 'light',
    colors: {
      primary: '#a855f7',
      background: '#faf5ff',
      surface: '#f3e8ff',
      text: '#581c87',
      border: '#e9d5ff',
    },
  },
  {
    id: 'coffee',
    name: 'Кофе',
    description: 'Уютная коричневая тема',
    type: 'dark',
    colors: {
      primary: '#d97706',
      background: '#292524',
      surface: '#44403c',
      text: '#f5f5f4',
      border: '#57534e',
    },
  },
]
